version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
